---
- name: Install iptables service
  yum:
    name: iptables-services
    state: present
  become: true

- name: Enable and start iptables
  service:
    name: iptables
    state: started
    enabled: true
  become: true

- name: Deploy iptables configuration
  template:
    src: iptables-config.j2
    dest: /etc/sysconfig/iptables-config
  become: true

#- name: Flush the existing rules
#  iptables:
#    flush: true
#  become: yes
#  notify: restart iptables

- name: Create the NAT rule
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ public_interface }}"
    jump: MASQUERADE
    comment: Masquarade the outgoing traffic
  become: true
  notify: restart iptables

- name: Allow established connections from the public interface
  iptables:
    chain: FORWARD
    in_interface: "{{ public_interface }}"
    out_interface: "{{ private_interface }}"
    match: state
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow established connections from the public interface
  become: true
  notify: restart iptables

- name: Allow outgoing traffic
  iptables:
    chain: FORWARD
    in_interface: "{{ private_interface }}"
    out_interface: "{{ public_interface }}"
    jump: ACCEPT
    comment: Allow outgoing traffic
  become: true
  notify: restart iptables


