---

- name: Enable the traffic forwarding
  sysctl: 
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
  become: yes

- name: Set up firewalld
  include_task: firewalld.yml
  when: use_firewall == firewalld

- name: Set up iptables
  include_task: iptables.yml
  when: use_firewall == iptables

