---
- name: Enable the traffic forwarding
  sysctl: 
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
  become: yes

- name: Deploy iptables configuration
  template:
    src: iptables-config.j2
    dest: /etc/sysconfig/iptables-config
  become: yes

- name: Create the NAT rule
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ public_interface }}"
    jump: MASQUERADE
    comment: Masquarade the outgoing traffic
  become: yes

- name: Allow established connections from the public interface
  iptables:
    chain: FORWARD
    in_interface: "{{ public_interface }}"
    out_interface: "{{ private_interface }}"
    match: state
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow established connections from the public interface
  become: yes

- name: Allow outgoing traffic
  iptables:
    chain: FORWARD
    in_interface: "{{ private_interface }}"
    out_interface: "{{ public_interface }}"
    jump: ACCEPT
    comment: Allow outgoing traffic
  become: yes